-- ============================================================
-- APNATRADE COMPLETE DATABASE SETUP
-- Version: 2.0 - Ultra Security Edition
-- ============================================================
--
-- HOW TO CREATE ADMIN:
-- ====================
-- 1. Sign up normally through the app with your admin email
-- 2. Run this SQL in Supabase SQL Editor:
--
--    INSERT INTO public.user_roles (user_id, role)
--    SELECT id, 'admin'::app_role
--    FROM auth.users 
--    WHERE email = 'selfashad@gmail.com';
--
-- 3. Admin Panel URL: /apnadradeadmin/auth
--    Password: @Mohammad_Ashad00####
--
-- ============================================================
-- This file contains the complete schema exported from the
-- running database. All tables, functions, triggers, RLS 
-- policies, and security measures are included.
--
-- For fresh setup, run all migrations in supabase/migrations/
-- or import this file to a new Supabase project.
-- ============================================================

-- See supabase/migrations/ folder for all SQL migrations
-- The database is automatically managed by Lovable Cloud

-- KEY SECURITY FEATURES:
-- ✅ RBAC with has_role() security definer function
-- ✅ Hash-chained financial audit logs (tamper-evident)
-- ✅ Atomic balance mutations via mutate_balance() RPC
-- ✅ Idempotency protection for all financial operations
-- ✅ Rate limiting with escalating blocks
-- ✅ Payout circuit breakers (hourly/daily limits)
-- ✅ IP blocklist and honeypot traps
-- ✅ User security profiles with risk scoring
-- ✅ Login history with impossible travel detection
-- ✅ Kill-switches for deposits/withdrawals/trades

-- PLATFORM LOGIC:
-- ✅ 30% win probability (rigged fair play)
-- ✅ 85% return rate on wins
-- ✅ Bet limits: ₹10 - ₹5000
-- ✅ Deposit limits: ₹100 - ₹5000
-- ✅ Withdrawal limits: ₹200 - ₹5000
-- ✅ Must bet deposit amount before withdrawing
