// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Environment validation for production
if (!SUPABASE_URL) {
  throw new Error('Missing VITE_SUPABASE_URL environment variable');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable');
}

// Validate URL format
try {
  new URL(SUPABASE_URL);
} catch {
  throw new Error('Invalid VITE_SUPABASE_URL format');
}

console.log('[Supabase] Initializing client:', {
  url: SUPABASE_URL.replace(/https?:\/\/[^.]+\./, 'https://***.'),
  hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  env: import.meta.env.MODE
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'apnatrade-web',
    },
  },
});
